### ISSUE TITLE
*** No rule to make target `@VMODTOOL@', needed by `vcc_if.c'.  Stop.

### ISSUE THREAD

**Issue by MrAbaddon** [kenshaw/libvmod-dns#7]
Trying to compile gives an error when running make:

*** No rule to make target `@VMODTOOL@', needed by `vcc_if.c'.  Stop.

I have a centos 6.5 machine.
Installed varnish via yum and have these RPM:

varnish-libs-3.0.7-1.el6.x86_64
varnish-libs-devel-3.0.7-1.el6.x86_64
varnish-release-3.0-1.el6.noarch
varnish-3.0.7-1.el6.x86_64

Could you help please?

Regards,

Bruno Morais

**Comment by kenshaw** [comment]
If you are compiling this from the Git repository, then you need to use the 3.x branch since you are using varnish-3.0.7.
